name: Reusable Docs Workflow

on: 
  workflow_call:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_dir: ${{ steps.find-docs-dir.outputs.docs_dir }}
      should_run: ${{ steps.check-changes.outputs.should_run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Find Docusaurus directory
        id: find-docs-dir
        shell: bash
        run: |
          doc_dir=$(find . -name "docusaurus.config.js" -exec dirname {} \;)
          echo "docs_dir=$doc_dir" >> "$GITHUB_OUTPUT"

      - name: Check for changes in Docusaurus directory
        id: check-changes
        run: |
          diff=$(git diff --name-only HEAD^ HEAD)

          if 

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          source_diff=$(echo "$diff" | grep -E '^${{ steps.find-docs-dir.outputs.docs_dir }}\/' || true)
          has_diff=false

          if [[ -n $source_diff ]]; then
            has_diff=true
          fi

          echo "should_run=$has_diff" >> "$GITHUB_OUTPUT"

  your_job:
    needs: [check_changes]
    if: needs.check_changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Your Step Name
        run: echo "Running your job as there were changes in the Docusaurus directory"
