name: Reusable Docs Workflow

on: 
  workflow_call:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      docs_dir: ${{ steps.find-docs-dir.outputs.docs_dir }}
      should_run: ${{ steps.check-changes.outputs.should_run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Find Docusaurus directory
        id: find-docs-dir
        shell: bash
        run: |
          doc_dir=$(find . -name "docusaurus.config.js" -exec dirname {} \;)
          echo "docs_dir=$doc_dir" >> "$GITHUB_OUTPUT"

      - name: Check for changes in Docusaurus directory
        id: check-changes
        shell: pwsh
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD

          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^docs/' -or $_ -match '.md$' }
          $HasDiff = $SourceDiff.Length -gt 0

          echo "should_run=$HasDiff" >> "$GITHUB_OUTPUT"

  your_job:
    needs: [check_changes]
    if: needs.check_changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Your Step Name
        run: echo "Running your job as there were changes in the Docusaurus directory"
